name: vishrampoint
description: A flutter project starting point to get started with flutter projects with ease and some awesome built in features.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5
  http: ^0.13.4
  get: ^4.6.5
  get_storage: ^2.0.3
  google_fonts: ^4.0.4
  flutter_svg: ^1.1.1+1
  image_picker: ^0.8.5+3
  razorpay_flutter: ^1.3.4
  screenshot: ^2.1.0
  clipboard: ^0.1.3
  share_plus: ^5.0.0
  flutter_countr:
    path: packages/flutter_countr
  ui_x:
    path: packages/ui_x
  connectivity_plus: ^2.3.6
  feather_icons: ^1.2.0
  flutter_image_slideshow: ^0.1.4
  sms_autofill: ^2.2.0
  mock_data: ^2.0.0
  date_format: ^2.0.7
  jiffy: ^5.0.0
  flutter_webview_pro: ^3.0.1+4
  camera: ^0.10.0+3
  firebase_core: ^2.4.1
  firebase_messaging: ^14.2.1
  firebase_performance: ^0.9.0+10
  firebase_crashlytics: ^3.0.11
  flutter_local_notifications: ^13.0.0
  just_audio: ^0.9.31
  google_translator: ^1.0.0
  vibration: ^1.7.6
  permission_handler: ^10.1.0
  pdf: ^3.8.4
  flutter_launcher_icons: ^0.11.0
  google_maps_flutter: ^2.2.3
  logger: ^1.1.0
  file_picker: ^5.0.1
  responsive_builder: ^0.7.0
  modulr:
    path: packages/modulr
  percent_indicator: ^4.2.3
  shimmer_animation: ^2.1.0+1
  country_list_pick: ^1.0.1+6






#  firebase_core:
#  firebase_messaging:
#  flutter_local_notifications:

dev_dependencies:
  flutter_test:
    sdk: flutter
#flutter_launcher_icons: ^0.11.0
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/system/launcher_icon.jpg"

  recase: ^4.0.0



# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/font/
    - assets/placeholders/
    - assets/system/
    - assets/

  fonts:
    - family: Quicksand-Medium
      fonts:
        - asset: assets/font/Quicksand-Medium.ttf
        - asset: assets/font/Quicksand-Bold.ttf
        - asset: assets/font/Quicksand-Light.ttf
        - asset: assets/font/Quicksand-Regular.ttf

